### ISSUE TITLE
Update language and merge checkboxes in program selection page

### ISSUE THREAD

**Issue by bestes-usds** [newjersey/dhs-oneapp#414]
**Screenshot of quick submit screen**
![Screen Shot 2020-11-23 at 1.40.41 PM.png](https://images.zenhubusercontent.com/5f579fdff369d2367fddffb6/f3413faa-d06f-415d-be39-d4883a955c66)

**Design principle**
- Copy should be written in simple, clear, and plain language in short, concise paragraphs
- Simplify the application, renewal, and reporting workflow
- Instead of making clients tell you which programs they want to apply to, let them tell you about their circumstances and then tell them which programs they're eligible for (we're in conflict with this, but I'm not sure how to avoid this without throwing a screener up)

**Recommendation**
- Consider replacing names of specific programs with more accessible language used on homepage:
  - Replace SNAP with "Food Assistance"
  - Consolidate TANF and GA into one "Cash Assistance" checkbox???  If NJ can determine what cash assistance program they're eligible for (i.e., from a question about kids) then applicants don't need to figure out if TANF or GA is the right one for them. According to the paper requirements tab in Melissa's spreadsheet, applicants for these 2 programs generally receive the same questions except in 3 areas:
    - childcare provider name (TANF only)
    - emergency contact (GA only)
    - screening for criminal conviction and sentence length (GA only)

- Also, may want to bounce this off NJ before reworking this page.

**Comparison State**
https://demo.michiganbenefits.org/sections/which-programs
![Screen Shot 2020-11-23 at 1.47.18 PM.png](https://images.zenhubusercontent.com/5f579fdff369d2367fddffb6/607fa640-ce06-4f38-88d1-8857d476d907)

**Comment by allyceh** [comment]
@bestes-usds Glad you flagged this-- there are a bunch of comments on the [prototype](https://dhs.invisionapp.com/share/NDYOY3WXCUR#/screens/426634092/comments) about this screen, so we'll have to tweak it. 

Juan: "I think I told them that we can't stop an applicant from applying for both GA and TANF. Maybe put language advising not to apply for both as they can only be eligible for one form of WFNJ?"
Alecia: "We shouldn't allow them to pick TANF and GA. Must be one or the other or neither of the two. If neither of the two, SNAP must be selected or an error will incur."

and

Alecia: "And what if they're not sure? We should have language in here that says either to check as many as they want if unsure or that they can add later in the application."

Let's consolidate TANF and GA into one checkbox and propose this to NJ, instead of using error messaging or validation. @melissajschaff , what do you think? 
Would the question for NJ be: can caseworkers determine eligibility for both programs if applicants select the "cash assistance" checkbox and communicate this to applicants? Or, what validations does OneApp have to help applicants determine if they are eligible for cash assistance while they are filling out the app? (Ron can probably answer that one)

**Comment by melissajschaff** [comment]
@bestes-usds @allyceh I'm going to run through designs this afternoon and make content updates

**Comment by melissajschaff** [comment]
updated prototype with a combined checkbox and program descriptions. Added program names to descriptions to clarify the second checkbox option with 2 programs.
